/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appshuttlecock;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class f_utama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(f_utama.class.getName());

    /**
     * Creates new form f_utama
     */
    public f_utama() {
        initComponents();
        subsetting.setVisible(false);
        pcontent.add(new p_dashboard());
        pcontent.repaint();
        pcontent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        putama = new javax.swing.JPanel();
        ptop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tusernametop = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttanggaltop = new javax.swing.JLabel();
        bclose = new javax.swing.JButton();
        pcenter = new javax.swing.JPanel();
        psidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        bdashboard = new javax.swing.JButton();
        bstok = new javax.swing.JButton();
        bpenjualan = new javax.swing.JButton();
        blaporan = new javax.swing.JButton();
        bsetting = new javax.swing.JButton();
        subsetting = new javax.swing.JPanel();
        bmanajemenuser = new javax.swing.JButton();
        babout = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        pcontent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        putama.setBackground(new java.awt.Color(255, 255, 255));
        putama.setLayout(new java.awt.BorderLayout());

        ptop.setBackground(new java.awt.Color(47, 79, 124));
        ptop.setPreferredSize(new java.awt.Dimension(1280, 75));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/SUPER P SHUTLE.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER :");

        tusernametop.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        tusernametop.setForeground(new java.awt.Color(255, 255, 255));
        tusernametop.setText("USERNAME");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TANGGAL :");

        ttanggaltop.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        ttanggaltop.setForeground(new java.awt.Color(255, 255, 255));
        ttanggaltop.setText("DD-MM-YYYY");

        bclose.setBackground(new java.awt.Color(47, 79, 124));
        bclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/Cancel White.png"))); // NOI18N
        bclose.setBorder(null);
        bclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ptopLayout = new javax.swing.GroupLayout(ptop);
        ptop.setLayout(ptopLayout);
        ptopLayout.setHorizontalGroup(
            ptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptopLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tusernametop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttanggaltop)
                .addGap(60, 60, 60)
                .addComponent(bclose)
                .addContainerGap())
        );
        ptopLayout.setVerticalGroup(
            ptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptopLayout.createSequentialGroup()
                .addGroup(ptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addGroup(ptopLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tusernametop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(ttanggaltop))))
                .addContainerGap())
            .addGroup(ptopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bclose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        putama.add(ptop, java.awt.BorderLayout.PAGE_START);

        pcenter.setBackground(new java.awt.Color(255, 255, 255));
        pcenter.setLayout(new java.awt.BorderLayout());

        psidebar.setBackground(new java.awt.Color(67, 114, 180));
        psidebar.setPreferredSize(new java.awt.Dimension(270, 720));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel5.setBackground(new java.awt.Color(67, 114, 180));

        bdashboard.setBackground(new java.awt.Color(255, 255, 255));
        bdashboard.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bdashboard.setForeground(new java.awt.Color(67, 114, 180));
        bdashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/ICON DASHBOARD.png"))); // NOI18N
        bdashboard.setText(" DASHBOARD");
        bdashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdashboardActionPerformed(evt);
            }
        });

        bstok.setBackground(new java.awt.Color(255, 255, 255));
        bstok.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bstok.setForeground(new java.awt.Color(67, 114, 180));
        bstok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/Stock Icon.png"))); // NOI18N
        bstok.setText(" STOK");
        bstok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bstok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstokActionPerformed(evt);
            }
        });

        bpenjualan.setBackground(new java.awt.Color(255, 255, 255));
        bpenjualan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bpenjualan.setForeground(new java.awt.Color(67, 114, 180));
        bpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/Penjualan Icon.png"))); // NOI18N
        bpenjualan.setText(" PENJUALAN");
        bpenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bpenjualan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpenjualanActionPerformed(evt);
            }
        });

        blaporan.setBackground(new java.awt.Color(255, 255, 255));
        blaporan.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        blaporan.setForeground(new java.awt.Color(67, 114, 180));
        blaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/Laporan Icon.png"))); // NOI18N
        blaporan.setText(" LAPORAN");
        blaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaporanActionPerformed(evt);
            }
        });

        bsetting.setBackground(new java.awt.Color(255, 255, 255));
        bsetting.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        bsetting.setForeground(new java.awt.Color(67, 114, 180));
        bsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/Setting Icon.png"))); // NOI18N
        bsetting.setText(" SETTING");
        bsetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsetting.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsettingActionPerformed(evt);
            }
        });

        subsetting.setBackground(new java.awt.Color(67, 114, 180));

        bmanajemenuser.setBackground(new java.awt.Color(255, 255, 255));
        bmanajemenuser.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bmanajemenuser.setForeground(new java.awt.Color(67, 114, 180));
        bmanajemenuser.setText("MANAJEMEN USER");
        bmanajemenuser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bmanajemenuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmanajemenuserActionPerformed(evt);
            }
        });

        babout.setBackground(new java.awt.Color(255, 255, 255));
        babout.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        babout.setForeground(new java.awt.Color(67, 114, 180));
        babout.setText("ABOUT");
        babout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        babout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baboutActionPerformed(evt);
            }
        });

        blogout.setBackground(new java.awt.Color(255, 255, 255));
        blogout.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        blogout.setForeground(new java.awt.Color(67, 114, 180));
        blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appshuttlecock/IMG/ICON LOGOUT.png"))); // NOI18N
        blogout.setText(" LOG OUT");
        blogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subsettingLayout = new javax.swing.GroupLayout(subsetting);
        subsetting.setLayout(subsettingLayout);
        subsettingLayout.setHorizontalGroup(
            subsettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bmanajemenuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(babout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(blogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subsettingLayout.setVerticalGroup(
            subsettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subsettingLayout.createSequentialGroup()
                .addComponent(bmanajemenuser, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(babout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subsetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bstok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bpenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsetting, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bstok, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bpenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(blaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bsetting, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subsetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout psidebarLayout = new javax.swing.GroupLayout(psidebar);
        psidebar.setLayout(psidebarLayout);
        psidebarLayout.setHorizontalGroup(
            psidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        psidebarLayout.setVerticalGroup(
            psidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );

        pcenter.add(psidebar, java.awt.BorderLayout.LINE_START);

        pcontent.setBackground(new java.awt.Color(224, 224, 224));
        pcontent.setPreferredSize(new java.awt.Dimension(1029, 645));
        pcontent.setLayout(new java.awt.CardLayout());
        pcenter.add(pcontent, java.awt.BorderLayout.CENTER);

        putama.add(pcenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(putama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(putama, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdashboardActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_dashboard());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bdashboardActionPerformed

    private void bstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstokActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_stock());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bstokActionPerformed

    private void bpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpenjualanActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_penjualn());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bpenjualanActionPerformed

    private void blaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaporanActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_laporan());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_blaporanActionPerformed

    private void bsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsettingActionPerformed
        // TODO add your handling code here:
        if (subsetting.isVisible()) {
        subsetting.setVisible(false);  // Sembunyikan
    } else {
        subsetting.setVisible(true);   // Tampilkan
    }
    }//GEN-LAST:event_bsettingActionPerformed

    private void bmanajemenuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmanajemenuserActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_manajemenuser());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bmanajemenuserActionPerformed

    private void baboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baboutActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_about());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_baboutActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
        new f_confir().setVisible(true);
        
    }//GEN-LAST:event_blogoutActionPerformed

    private void bcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        System.out.println("OOn");
        
    }//GEN-LAST:event_bcloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.arc", 15
            );
            
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new f_utama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton babout;
    private javax.swing.JButton bclose;
    private javax.swing.JButton bdashboard;
    private javax.swing.JButton blaporan;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bmanajemenuser;
    private javax.swing.JButton bpenjualan;
    private javax.swing.JButton bsetting;
    private javax.swing.JButton bstok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pcenter;
    private javax.swing.JPanel pcontent;
    private javax.swing.JPanel psidebar;
    private javax.swing.JPanel ptop;
    private javax.swing.JPanel putama;
    private javax.swing.JPanel subsetting;
    private javax.swing.JLabel ttanggaltop;
    private javax.swing.JLabel tusernametop;
    // End of variables declaration//GEN-END:variables
}
